### ISSUE TITLE
How do I configure tests to run in babel stage=0

### ISSUE THREAD

**Issue by yakirn** [newtriks/generator-react-webpack#165] opened 2015-11-13 15:33 UTC
I've modified cfg/dev.js to support stage 0 features of babel:
```
config.module.loaders.push({
  test: /\.(js|jsx)$/,
  loader: 'react-hot!babel-loader?stage=0',
  include: path.join(__dirname, '/../src')
});
```
then I added a stage 0 feature such as class properties to src/components.Main.js
```
myProp=42;
render(){
...
}
```
https://github.com/jeffmo/es-class-static-properties-and-fields

hit npm start, and everything works fine.

I've noticed  cfg/test.js has two babel loaders (the second is for test coverage?)
I tried to add stage=0 for the first one and for both as a query string, using the two options that are suggested here (query string and query property):
https://github.com/babel/babel-loader/tree/v5.3.2#options

either way, running `npm test` fails with syntax error where the stage 0 code is.
any idea how to solve this?
Thanks!

**Comment by sthzg** [comment] 2015-11-13 21:59
@yakirn fwiw,there is a related issue targeting the update from babel 5 to 6 in the repository that features the template used in this generator. not sure if they are related, but it might be interesting either way weblogixx/react-webpack-template/issues/11.

**Comment by weblogixx** [comment] 2015-11-16 06:41
Hi @yakirn,

currently we are still using babel 5, so there may be some stuff that is currently not working.
I currently wait for https://github.com/deepsweet/isparta-loader to update the isparta dependency for coverage reports. If the update is done, it should work as intended.

**Comment by yakirn** [comment] 2015-11-16 07:46
@weblogixx @sthzg Thank you for your answers.
So, if I understand correctly, isparta-loader is just about code coverage?
if removing isparta will make my tests work without coverage, it is good enough for me, at least until a real fix/update will be available. can you instruct me on how to do this?
Thanks again

**Comment by weblogixx** [comment] 2015-11-16 07:51
@yakirn,

yes, it should work when you disable the isparta-loading and update to babel 6. I have all parts ready but unfortunately still have to wait for isparta-loader to be updated. If this is not happening in the nearer future, I will have to disable it (or fork the project, the change that needs to be done is just updating the package.json).

**Comment by weblogixx** [comment] 2015-11-17 06:58
@yakirn: The generator was just updated to use babel 6. It should work with the new version without problems. Note: Only newly created projects (after updating the generator) will be build with babel 6.

**Comment by weblogixx** [comment] 2015-11-18 07:11
@yakin:
Yes, the new loaders author has choosen to "update" his isparta loader with the old isparta config for versions 0.2.x. So it ran when it was 0.2.2, but no more for 0.2.3 :(. A new version of the template will be available in a couple of minutes, the dependency is fixed then. Just update your generator in about half an hour to make it work correctly.

**Comment by weblogixx** [comment] 2015-11-19 06:25
Think that should be done with the update. Closing this. If there are any other errors, feel free to open a new ticket.

**Closed by weblogixx** 2015-11-19 06:25 UTC
